language: objective-c
osx_image: xcode7.3
script:
  xcodebuild
  -project MorMessages.xcodeproj
  -scheme MorMessages-Travis
  build
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
